### PR TITLE
Add a python script to create a Xlsx report from the collected info.

### PR DESCRIPTION
**Pull request by pilhuhn**
This python script creates a .xlsx file in the reports/ directory. 
It removes 'undefined' and 'null' values from cells, freezes the name column + header row.
Also columns sizes are adjusted.

### CODE REVIEW

**Comment by evwilkin** [comment]
Thanks for the contribution!  I ran into a couple issues when running this code:

1. Dates in `cli.js` and `to_xls.py` can mismatch, throwing `FileNotFoundError: [Errno 2] No such file or directory: 'stats-static/2024-07-28'`:
  - `const date = new Date().toISOString();`
  - `today = datetime.today()`
  - We can update the JS in `cli.js` to match the python code but that would make the report date dependent of the location of the machine running the report - for consistency does python have an equivalent to the `Date.prototype.toISOString` function?
2. Had to [change capitalization](https://xlsxwriter.readthedocs.io/getting_started.html#using-pip) in the following to work correctly:
  - `pip install XlsxWriter`
3. The output file `repos_all.xlsx` only has one row, with data for `Cost-Management-Cost-Management`
  - I did try running the code separately with `do_collect = True` and confirmed the data is being collected correctly, so I'm not sure if the .xlsx file is being overwritten with each new codebase or is exiting out early after one pass for some reason?

**Comment by pilhuhn** [comment]
I am looking into this. I think for the date, the JS code uses a UTC timezone, while my python code doesn't do that yet.

**Comment by pilhuhn** [comment]
The .xlsx is rewritten on each run. 
For Cost-management, the .csv file produced by cli.js only has one line for me.

**Review by evwilkin — APPROVED** [review]
LGTM - thanks for the updates! 🎉

**Pull request merged**
